### ISSUE TITLE
Any chance of a posterization style effect?

### ISSUE THREAD

**Issue by Fritomaster** [truepak/UnityTexelShaders#4]
Is there any way you can add in a posterization effect? So the light has more noticable steps? 

I'm working on a 3D pixel art game not really using PBR. But looking for per texel shading + less gradient shadows for lighting.

**Comment by keeborgue** [comment]
I believe that's doable. [I can add this code](https://docs.unity3d.com/Packages/com.unity.shadergraph@6.9/manual/Posterize-Node.html) and Vector4 parameter (1 for each color + alpha) as a step count control variable directly in material parameter inspector.

**Comment by keeborgue** [comment]
[Done](https://github.com/truepak/UnityTexelShaders/commit/f84a343bd62b3b965f873e7d2ba95429fbcb37bf), Added PosterizationStepCount parameter. Custom lit editor gui is turned off for now, as it ignores the parameter in inspector.

**Comment by Fritomaster** [comment]
> [Done](https://github.com/truepak/UnityTexelShaders/commit/f84a343bd62b3b965f873e7d2ba95429fbcb37bf), Added PosterizationStepCount parameter. Custom lit editor gui is turned off for now, as it ignores the parameter in inspector.

Thanks. Gonna test it now. 

Edit: So its a cool effect and may be useful for someone. 

I guess posterization isn't what I was looking for.  I'm trying to find a way so the lights work in steps. While the posterization kinda shows the idea it crushes all the colors.

I just want to reduce the amount of colors in the lighting to a smaller amount of steps. 
Appreciate the work tho. Its a cool effect.

**Comment by keeborgue** [comment]
> I just want to reduce the amount of colors in the lighting to a smaller amount of steps.

Actually, I've added an option to posterize light exclusively.
Check out [latest commit](https://github.com/truepak/UnityTexelShaders/commit/c67262f61beb9809464fddbe810dbdcae3b6b5db). Use "Light Posterization Step Count" property on material. W-axis does not do anything.

**Comment by Fritomaster** [comment]
> > I just want to reduce the amount of colors in the lighting to a smaller amount of steps.
> 
> Actually, I've added an option to posterize light exclusively.
> Check out [latest commit](https://github.com/truepak/UnityTexelShaders/commit/c67262f61beb9809464fddbe810dbdcae3b6b5db). Use "Light Posterization Step Count" property on material. W-axis does not do anything.

Great work. Sadly though we swapped to HDRP. Any chance of support for that?
